# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da1d7c2119a5099c064eb0a2f7ec61f960a7e17f816e13d496f0254982f7aa825f35a43f2ebd045efba79b38d881b590813a4a490c3b25be32183eee02ec3f11

test:
  secret_key_base: 7590199b19b5ed98d98c27c2867821cae23671f9f20c587dd9ca0746464625540e0af63a312dad4787e7cf4aa86e9337a992037c31690ed8e43714c65ce52423

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
